# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "docker.io/techbcknd/hello-world:latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "hello-world"
fullnameOverride: "hello-world"

serviceAccount:
  # Specifies whether a service account should be created
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
